version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  frontend:
    build: ./frontend
    ports:
      - 5001:5000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
